# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170715_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
