# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170715_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.NutrientGroup'),
        ),
    ]
