# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_animal_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='servingSize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='servingUnit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
