# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_food_kilojouls'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodNutrients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('quantityUnit', models.CharField(max_length=5)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
                ('nutrient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Nutrient')),
            ],
        ),
    ]
