# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_foodnutrients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodnutrients',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
