# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20170719_2253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodNutrients',
            new_name='FoodNutrient',
        ),
    ]
