# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20170719_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('quantityUnit', models.CharField(max_length=5)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Animal')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Nutrient')),
            ],
        ),
    ]
