# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_meal_mealfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealfood',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='mealfood',
            name='quantityUnit',
            field=models.CharField(default='g', max_length=5),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='quantityUnit',
            field=models.CharField(default='g', max_length=5),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
