# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_meal_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='nutrition',
            field=models.ManyToManyField(through='food.FoodNutrient', to='food.Nutrient'),
        ),
    ]
