# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_food_nutrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
